ENT.Type 			= "anim"
ENT.Base 			= "base_gmodentity"
ENT.Category		= "Stargate"
ENT.PrintName		= "Missile"
ENT.Author			= "thebigalex, Cartman300"

ENT.Spawnable			= true
ENT.AdminSpawnable		= false
ENT.follow			= nil
ENT.Owner			= nil
ENT.Exploded			= false
ENT.FuelAmount			= 1000000
ENT.LastPosition		= Vector(0,0,0)
ENT.XCo				= nil
ENT.YCo				= nil
ENT.ZCo				= nil
ENT.Launched			= false
ENT.Armed			= false
ENT.Target			= Vector(0,0,0)
ENT.PhysObj			= nil
ENT.Locked			= false
ENT.PreLaunch			= false
ENT.Warhead			= "exp_head"
ENT.WHConfig			= true