ENT.Type 			= "anim"
ENT.Base 			= "base_gmodentity"
ENT.PrintName		= "Missile Launcher"
ENT.Author			= "Cartman300"
ENT.Category		= "Stargate"

ENT.Spawnable		= true
ENT.AdminSpawnable	= true
ENT.Owner			= nil
ENT.Exploded		= false
ENT.XCo				= nil
ENT.YCo				= nil
ENT.ZCo				= nil
ENT.Armed			= false
ENT.Target			= Vector(0,0,0)
ENT.PhysObj			= nil
ENT.Locked			= false
ENT.LTime			= 1000000
ENT.Launched		= 0
